language: node_js
node_js:
  - "v12.13.1"
branches:
  only:
  - master
notifications:
  email:
    recipients:
      - 64048861@qq.com
    on_success: always # default: change
    on_failure: always # default: alway
cache:
  directories:
  - node_modules
  yarn: true
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
install:
 - npm install -g gitbook-cli
script:
- gitbook build ./ ./docs
# deploy:
#   provider: pages # deploy to GitHub Pages
#   skip_cleanup: true # don't clean generated site
#   github_token: $TOKEN # provide the encrypted token
#   local-dir: ./docs/ ## 根据情况自定义到静态文件输出目录
#   on:
#     branch: master
#   repo: ceeyang/FlutterInterview/ # optional, defaults to current repo
#   target_branch: master # optional, defaults to "gh-pages"
#   email: yangxichuan2016@gmail.com # optional, defaults to "deploy@travis-ci.org"
#   name: ceeyang # optional, defaults to "Deployment Bot"

after_script:
   - cd docs
   - git init
   - git config user.name "ceeyang"
   - git config user.email "64048861@qq.com"
   - git add .
   - git commit -m "Update Gitbook By TravisCI With Build $TRAVIS_BUILD_NUMBER"
   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages